#!/bin/bash
set -euo pipefail

# safe-ai proxy entrypoint
# Reads allowlist.yaml + SAFE_AI_DEFAULT_DOMAINS env, generates squid.conf,
# then starts Squid.

ALLOWLIST_FILE="/etc/safe-ai/allowlist.yaml"
SQUID_CONF="/etc/squid/squid.conf"

# ---- Generate squid.conf ----

cat > "$SQUID_CONF" <<'HEADER'
# Auto-generated by safe-ai proxy entrypoint.
visible_hostname safe-ai-proxy

http_port 3128

acl Safe_ports port 80
acl Safe_ports port 443
acl SSL_ports port 443
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports

HEADER

# ---- Collect domains from file + env ----

DOMAINS=""

if [ -f "$ALLOWLIST_FILE" ]; then
    FILE_DOMAINS=$(yq -r '.domains[]' "$ALLOWLIST_FILE" 2>/dev/null || true)
    if [ -n "$FILE_DOMAINS" ]; then
        DOMAINS="$FILE_DOMAINS"
    fi
fi

if [ -n "${SAFE_AI_DEFAULT_DOMAINS:-}" ]; then
    IFS=',' read -ra ENV_DOMAINS <<< "$SAFE_AI_DEFAULT_DOMAINS"
    for d in "${ENV_DOMAINS[@]}"; do
        d=$(echo "$d" | xargs)
        if [ -n "$d" ]; then
            DOMAINS="${DOMAINS}${DOMAINS:+$'\n'}${d}"
        fi
    done
fi

# ---- Generate dnsmasq.conf ----

DNSMASQ_CONF="/etc/dnsmasq.d/safe-ai.conf"
mkdir -p /etc/dnsmasq.d

cat > "$DNSMASQ_CONF" <<'DNSHEADER'
# Auto-generated by safe-ai proxy entrypoint.
# Block all DNS by default, only forward allowlisted domains.
no-resolv
no-hosts
address=/#/
port=53
listen-address=0.0.0.0
log-queries
log-facility=-
DNSHEADER

if [ -n "$DOMAINS" ]; then
    while IFS= read -r domain; do
        domain=$(echo "$domain" | xargs)
        [ -z "$domain" ] && continue
        [[ "$domain" == \#* ]] && continue
        domain="${domain#.}"
        echo "server=/${domain}/8.8.8.8" >> "$DNSMASQ_CONF"
        echo "server=/${domain}/8.8.4.4" >> "$DNSMASQ_CONF"
    done <<< "$DOMAINS"
fi

# ---- Write domain ACLs ----

if [ -n "$DOMAINS" ]; then
    echo "# Allowed domains" >> "$SQUID_CONF"
    while IFS= read -r domain; do
        domain=$(echo "$domain" | xargs)
        [ -z "$domain" ] && continue
        [[ "$domain" == \#* ]] && continue
        if [[ "$domain" == .* ]]; then
            echo "acl safe_ai_allowed dstdomain ${domain}" >> "$SQUID_CONF"
        else
            echo "acl safe_ai_allowed dstdomain .${domain}" >> "$SQUID_CONF"
        fi
    done <<< "$DOMAINS"
    echo "" >> "$SQUID_CONF"
fi

# ---- Gateway token injection ----
# If /etc/safe-ai/gateway.conf exists (baked in by org), or env vars are set,
# inject X-Safe-AI-Token header on requests to the gateway domain.
GATEWAY_CONF="/etc/safe-ai/gateway.conf"
GW_DOMAIN="${SAFE_AI_GATEWAY_DOMAIN:-}"
GW_TOKEN="${SAFE_AI_GATEWAY_TOKEN:-}"

if [ -f "$GATEWAY_CONF" ]; then
    GW_DOMAIN=$(grep '^domain=' "$GATEWAY_CONF" | cut -d= -f2-)
    GW_TOKEN=$(grep '^token=' "$GATEWAY_CONF" | cut -d= -f2-)
fi

if [ -n "$GW_DOMAIN" ] && [ -n "$GW_TOKEN" ]; then
    GW_DOMAIN="${GW_DOMAIN#.}"

    # Add gateway to DNS + Squid allowlist
    echo "server=/${GW_DOMAIN}/8.8.8.8" >> "$DNSMASQ_CONF"
    echo "server=/${GW_DOMAIN}/8.8.4.4" >> "$DNSMASQ_CONF"
    echo "acl safe_ai_allowed dstdomain .${GW_DOMAIN}" >> "$SQUID_CONF"

    # Gateway-specific ACL + anti-spoof + header injection
    cat >> "$SQUID_CONF" <<GATEWAY
# Gateway origin token (org-provisioned)
acl safe_ai_gateway dstdomain .${GW_DOMAIN}
request_header_access X-Safe-AI-Token deny all
request_header_add X-Safe-AI-Token "${GW_TOKEN}" safe_ai_gateway
GATEWAY

    echo "[safe-ai] Gateway token configured for ${GW_DOMAIN}"
fi

# ---- Access rules ----

cat >> "$SQUID_CONF" <<'RULES'
# Allow CONNECT (HTTPS) to permitted domains
http_access allow CONNECT safe_ai_allowed

# Allow HTTP to permitted domains
http_access allow safe_ai_allowed

# DEFAULT DENY
http_access deny all

# SNI-based HTTPS filtering (peek-and-splice, no MITM)
ssl_bump peek all
ssl_bump splice all

# No caching — proxy is for access control only
cache deny all
maximum_object_size 0 KB

# Structured JSON access log for audit trail
logformat audit_json {"timestamp":"%tl","duration_ms":%tr,"client_ip":"%>a","method":"%rm","url":"%"ru","http_status":%>Hs,"squid_action":"%Ss","hierarchy":"%Sh","request_bytes":%>st,"response_bytes":%<st,"content_type":"%"mt","user_agent":"%"{User-Agent}>h","sni":"%ssl::>sni"}
access_log stdio:/var/log/squid/access.log audit_json
cache_log /var/log/squid/cache.log

coredump_dir /var/spool/squid
RULES

# ---- Print config summary ----

echo "[safe-ai] Proxy ready. Allowed domains:"
if [ -n "$DOMAINS" ]; then
    echo "$DOMAINS" | while IFS= read -r d; do
        d=$(echo "$d" | xargs)
        [ -n "$d" ] && [[ "$d" != \#* ]] && echo "  - $d"
    done
else
    echo "  (none — all outbound traffic will be blocked)"
fi
if [ -n "${GW_DOMAIN:-}" ] && [ -n "${GW_TOKEN:-}" ]; then
    echo "[safe-ai] Gateway: ${GW_DOMAIN} (token injected)"
fi

# ---- Start dnsmasq ----
dnsmasq --conf-file="$DNSMASQ_CONF"
echo "[safe-ai] DNS filter started."

# ---- Start SSH forwarder ----
# Port publishing doesn't work on Docker internal networks, so
# we forward SSH traffic through the proxy to the sandbox.
if [ -n "${SAFE_AI_SSH_FORWARD:-}" ]; then
    socat TCP-LISTEN:2222,fork,reuseaddr TCP:sandbox:22 &
    echo "[safe-ai] SSH forwarder started (port 2222 -> sandbox:22)."
fi

# ---- Start Squid ----
# Tail log files to stdout/stderr so docker compose logs works
touch /var/log/squid/access.log /var/log/squid/cache.log
chown squid:squid /var/log/squid/access.log /var/log/squid/cache.log
tail -F /var/log/squid/access.log &
tail -F /var/log/squid/cache.log >&2 &
exec squid -NYC -f "$SQUID_CONF"
